image: jangrewe/gitlab-ci-android

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew


stages:
  - release


assembleRelease:
  stage: release
  only:
    - tags

  script:
    - echo $KEYSTORE_BASE64 | base64 -d > keystore.jks
    - ./gradlew assembleRelease
      -Pandroid.injected.signing.store.file=$(pwd)/keystore.jks
      -Pandroid.injected.signing.store.password=$KEYSTORE_PASSWORD
      -Pandroid.injected.signing.key.alias=$GITLAB_KEY_ALIAS
      -Pandroid.injected.signing.key.password=$GITLAB_KEY_PASSWORD
    - ./create-release.sh
  artifacts:
    paths:
      - app/build/outputs/apk/release/battleships-release.apk
